package project_euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * <p/>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p/>
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

    public static int run() {
        return sumOfFiboTermsUptoTerm(4_000_000);
    }

    public static int sumOfFiboTermsUptoTerm(final int maxFibo) {
        int sum = 2;
        int previous = 1;
        int current = 2;
        while (true) {
            int nextFibo = current + previous;
            if (nextFibo > maxFibo)
                break;
            if ((nextFibo & 1) == 0) {
                sum += nextFibo;
            }
            previous = current;
            current = nextFibo;
        }
        return sum;
    }
}
